#!/bin/bash

SRC="gcc"

tar -xf ../mpfr-[0-9]*.tar.xz
mv -v mpfr-[0-9]* mpfr
tar -xf ../gmp-[0-9]*.tar.xz
mv -v gmp-[0-9]* gmp
tar -xf ../mpc-[0-9]*.tar.gz
mv -v mpc-[0-9]* mpc


sed 's@m64=.*@m64=../lib@;s@m32=.*@m32=../lib32@' -i.ori gcc/config/i386/t-linux64
sed '/ld.*-uClibc.so.0/s/0/1/' -i.ori gcc/config/linux.h

sed '/thread_header =/s/@.*@/gthr-posix.h/' \
	-i libgcc/Makefile.in libstdc++-v3/include/Makefile.in

mkdir -v build
cd build

case "$(uname -m)" in x86_64) _args="--with-arch=x86-64-v3";; esac

../configure \
	--build=$(../config.guess) \
	--host=$LFS_TGT \
	--target=$LFS_TGT \
	LDFLAGS_FOR_TARGET=-L$PWD/$LFS_TGT/libgcc \
	--prefix=/usr \
	--with-build-sysroot=$LFS \
	--enable-default-pie \
	--enable-default-ssp \
	--disable-nls \
	--$([[ $MULTILIB ]] && echo enable-multilib --with-multilib-list=m64,m32 || echo disable-multilib) \
	--disable-libatomic \
	--disable-libgomp \
	--disable-libquadmath \
	--disable-libsanitizer \
	--disable-libssp \
	--disable-libvtv \
	--enable-languages=c,c++ $_args

make
make DESTDIR=$LFS install
ln -sv gcc $LFS/usr/bin/cc
rm -fv $LFS/usr/lib{,32}/*.la

install -Dm755 /dev/stdin $LFS/usr/bin/c89 <<"EOF"
#!/bin/sh
fl="-std=c89"
for opt; do
  case "$opt" in
    -ansi|-std=c89|-std=iso9899:1990) fl="";;
    -std=*) echo "`basename $0` called with non ANSI/ISO C option $opt" >&2
            exit 1;;
  esac
done
exec cc $fl ${1+"$@"}
EOF

install -Dm755 /dev/stdin $LFS/usr/bin/c99 <<"EOF"
#!/bin/sh
fl="-std=c99"
for opt; do
  case "$opt" in
    -std=c99|-std=iso9899:1999) fl="";;
    -std=*) echo "`basename $0` called with non ISO C99 option $opt" >&2
            exit 1;;
  esac
done
exec cc $fl ${1+"$@"}
EOF
