#!/bin/bash

export BUILDDIR="/lfs_build"
export SRC_ARCHIVE="$BUILDDIR/sources"
export LFS="$BUILDDIR"
export log_dir="$PWD/log"

export BLD_ROOT="/alfs"
export SRC_ROOT="/sources"
export LOG_DIR="$BLD_ROOT/log"
export FILE_DIR="$BLD_ROOT/installed-files"

# wget-list channels
export channels="development" # stable 11.3 ... https://www.linuxfromscratch.org/lfs/downloads

case $(uname -m) in
	i?86)
		CFLAGS="-march=i686"
		;;
	x86_64)
		CFLAGS="-march=x86-64-v3"
		;;
	*)
		echo "$0: unknown or unsupported arch: $(uname -m)"
		exit 1
		;;
esac

export CFLAGS="$CFLAGS -mtune=haswell -Os -pipe -fno-plt -fPIC -fstack-clash-protection -ffunction-sections -fdata-sections"
export CXXFLAGS="$CFLAGS -Wp,-D_GLIBCXX_ASSERTIONS"
export CPPFLAGS="-DNDEBUG"
export LDFLAGS="-Wl,-O2,--sort-common,--as-needed,-z,relro,-z,now,--gc-sections"
export MAKEFLAGS="-j$(nproc)"
export NINJAJOBS="$(nproc)"
export NINJA_STATUS="[%r %f/%t %es] "
