#!/bin/bash

SRC="bzip2"
PKG="$SRC"

PV=${PWD##*/}
PV=${PV#bzip2-}

sed -i 's@\(ln -s -f \)$(PREFIX)/bin/@\1@' Makefile
sed -i "s@(PREFIX)/man@(PREFIX)/share/man@g" Makefile
make -f Makefile-libbz2_so
make clean

make
make PREFIX=/usr install
cp -av libbz2.so.* /usr/lib
ln -sv libbz2.so.$PV /usr/lib/libbz2.so
cp -v bzip2-shared /usr/bin/bzip2
for i in /usr/bin/{bzcat,bunzip2}; do
	ln -sfv bzip2 $i
done
rm -fv /usr/lib/libbz2.a


if [[ $MULTILIB ]]; then
	make clean
	sed -e "s/^CC=.*/CC=gcc -m32/" -i Makefile{,-libbz2_so}
	make -f Makefile-libbz2_so
	make libbz2.a
	install -Dvm755 libbz2.so.$PV /usr/lib32/libbz2.so.$PV
	ln -sfv libbz2.so.$PV /usr/lib32/libbz2.so
	ln -sfv libbz2.so.$PV /usr/lib32/libbz2.so.1
	ln -sfv libbz2.so.$PV /usr/lib32/libbz2.so.1.0
	install -Dvm644 libbz2.a /usr/lib32/libbz2.a
fi
