#!/bin/bash

SRC="readline"
PKG="$SRC"

sed -i '/MV.*old/d' Makefile.in
sed -i '/{OLDSUFF}/c:' support/shlib-install

./configure \
	--prefix=/usr \
	--disable-static \
	--with-curses

make SHLIB_LIBS="-lncursesw"
make SHLIB_LIBS="-lncursesw" install
install -Dvm644 doc/*.{ps,pdf,html,dvi} /usr/share/doc/readline


if [[ $MULTILIB ]]; then
	make distclean
	CC="gcc -m32" CXX="g++ -m32" \
	./configure --prefix=/usr \
		--libdir=/usr/lib32 \
		--disable-static \
		--with-curses
	make SHLIB_LIBS="-lncursesw"
	make SHLIB_LIBS="-lncursesw" DESTDIR=$PWD/pkg install
	cp -av pkg/usr/lib32/* /usr/lib32
fi
