#!/bin/bash

SRC="acl"
PKG="$SRC"

./configure --prefix=/usr \
	--disable-static

make
make install

if [[ $MULTILIB ]]; then
	make distclean
	CC="gcc -m32" CXX="g++ -m32" \
	./configure --prefix=/usr \
		--libdir=/usr/lib32 \
		--libexecdir=/usr/lib32 \
		--disable-static
	make
	make DESTDIR=$PWD/pkg install
	cp -av pkg/usr/lib32/* /usr/lib32
fi
