#!/bin/bash

SRC="libxcrypt"
PKG="$SRC"

./configure --prefix=/usr \
	--enable-hashes=strong \
	--enable-obsolete-api=no \
	--disable-failure-tokens

make
make install

if [[ $MULTILIB ]]; then
	make distclean
	CC="gcc -m32" CXX="g++ -m32" \
	./configure --prefix=/usr \
		--libdir=/usr/lib32 \
		--enable-hashes=strong \
		--enable-obsolete-api=no \
		--disable-failure-tokens
	make
	cp -av .libs/libcrypt.so* /usr/lib32/
	make install-pkgconfigDATA
	ln -svf libxcrypt.pc /usr/lib32/pkgconfig/libcrypt.pc
fi
