#!/bin/bash
# https://github.com/void-linux/void-packages/blob/master/srcpkgs/gettext/template

SRC="gettext"
PKG="$SRC"

./configure --prefix=/usr \
	--with-included-gettext

make
make install
rm -fv /usr/lib/libintl*.la

if [[ $MULTILIB ]]; then
	make distclean
	cd gettext-runtime
	CC="gcc -m32" CXX="g++ -m32" \
	./configure --prefix=/usr \
		--libdir=/usr/lib32
	make
	make DESTDIR=$PWD/pkg install
	cp -av pkg/usr/lib32/* /usr/lib32
fi
