#!/bin/bash
# https://www.linuxfromscratch.org/lfs/view/development/chapter08/perl.html

SRC="perl"
PKG="$SRC"

export BUILD_ZLIB=False
export BUILD_BZIP2=0

pkgver="$(find .. -maxdepth 1  -type f -name 'perl*.tar.*' -exec basename {} +|head -1)"
pkgver=${pkgver#perl-}
pkgver=${pkgver%.tar*}
_baseVER="${pkgver%.*}"

sh Configure -des \
	-Dprefix=/usr \
	-Dvendorprefix=/usr \
	-Dprivlib=/usr/lib/perl5/${_baseVER}/core_perl \
	-Darchlib=/usr/lib/perl5/${_baseVER}/core_perl \
	-Dsitelib=/usr/lib/perl5/${_baseVER}/site_perl \
	-Dsitearch=/usr/lib/perl5/${_baseVER}/site_perl \
	-Dvendorlib=/usr/lib/perl5/${_baseVER}/vendor_perl \
	-Dvendorarch=/usr/lib/perl5/${_baseVER}/vendor_perl \
	-Dman1dir=/usr/share/man/man1 \
	-Dman3dir=/usr/share/man/man3 \
	-Dpager="/usr/bin/less -isR" \
	-Duseshrplib \
	-Dldflags="${LDFLAGS}" \
	-Doptimize="${CFLAGS}"

make
make install
unset BUILD_ZLIB BUILD_BZIP2 pkgver _baseVER
