#!/bin/bash

SRC="kmod"
PKG="$SRC"

./configure --prefix=/usr \
	--sysconfdir=/etc \
	--with-openssl \
	--with-xz \
	--with-zstd \
	--with-zlib

make
make install
for target in depmod insmod modinfo modprobe rmmod; do
	ln -sfv ../bin/kmod /usr/sbin/$target
done
ln -sfv kmod /usr/bin/lsmod


if [[ $MULTILIB ]]; then
	sed -e "s/^CLEANFILES =.*/CLEANFILES =/" -i man/Makefile
	make clean
	CC="gcc -m32" CXX="g++ -m32" \
	./configure --prefix=/usr \
		--libdir=/usr/lib32 \
		--sysconfdir=/etc \
		--with-openssl \
		--with-xz \
		--with-zstd \
		--with-zlib \
		--with-rootlibdir=/usr/lib32
	make
	make DESTDIR=$PWD/pkg install
	cp -av pkg/usr/lib32/* /usr/lib32
fi
