#!/bin/bash

SRC="libffi"
PKG="$SRC"

./configure --prefix=/usr	\
	--disable-static	\
	--with-gcc-arch=native

make
make install

if [[ $MULTILIB ]]; then
	make distclean
	CC="gcc -m32" CXX="g++ -m32" \
	./configure --prefix=/usr \
		--libdir=/usr/lib32 \
		 --disable-static \
		--with-gcc-arch=i686
	make
	make DESTDIR=$PWD/pkg install
	cp -av pkg/usr/lib32/* /usr/lib32
fi
