#!/bin/bash

SRC="wheel"
PKG="python-$SRC"

pip3 --version
pip3 wheel -w dist --no-build-isolation --no-deps $PWD
pip3 install --no-index --find-links=dist wheel
if [ -d "$HOME/.cache" ]; then
	echo -e '\n'
	rm -rfv "$HOME/.cache"
fi
