#!/bin/bash

SRC="coreutils"
PKG="$SRC"

if [ -f lib/mcel.h ]; then
	sed -i 's/^#if defined __GLIBC__ /\0\&\& !defined __UCLIBC__ /' lib/mcel.h
fi

autoreconf -fiv
FORCE_UNSAFE_CONFIGURE=1 ./configure \
	--prefix=/usr \
	--enable-no-install-program=kill,uptime

make
make install
mv -v /usr/bin/chroot /usr/sbin
mv -v /usr/share/man/man1/chroot.1 /usr/share/man/man8/chroot.8
sed -i 's/"1"/"8"/' /usr/share/man/man8/chroot.8
