#!/bin/bash

SRC="coreutils"
PKG="$SRC"

autoreconf -fiv
FORCE_UNSAFE_CONFIGURE=1 ./configure \
	--prefix=/usr \
	--enable-no-install-program=kill,uptime

make
make install
mv -v /usr/bin/chroot /usr/sbin
mv -v /usr/share/man/man1/chroot.1 /usr/share/man/man8/chroot.8
sed -i 's/"1"/"8"/' /usr/share/man/man8/chroot.8
