#!/bin/bash

SRC="kbd"
PKG="$SRC"

sed -i '/RESIZECONS_PROGS=/s/yes/no/' configure
sed -i 's/resizecons.8 //' docs/man/man8/Makefile.in

CFLAGS+=" -lintl"
./configure --prefix=/usr --disable-vlock

make
make install
