#!/bin/bash

SRC="tar"
PKG="$SRC"

if [[ "$(uname -m)" == i?86 ]]; then
	_args="--disable-year2038"
fi

CFLAGS+=" -lintl"

FORCE_UNSAFE_CONFIGURE=1 \
./configure --prefix=/usr $_args

make
make install
