#!/bin/bash

SRC="util-linux"
PKG="$SRC"

sed -i '/test_mkfds/s/^/#/' tests/helpers/Makemodule.am

./configure  \
	--bindir=/usr/bin \
	--libdir=/usr/lib \
	--runstatedir=/run \
	--sbindir=/usr/sbin \
	--disable-chfn-chsh \
	--disable-login \
	--disable-nologin \
	--disable-su \
	--disable-setpriv \
	--disable-runuser \
	--disable-pylibmount \
	--disable-static \
	--without-python \
	ADJTIME_PATH=/var/lib/hwclock/adjtime

make
make install
