#!/bin/bash

SRC="e2fsprogs"
PKG="$SRC"

mkdir -v build
cd build

LDFLAGS="-Wl,-lintl $LDFLAGS"

../configure --prefix=/usr \
	--sysconfdir=/etc \
	--enable-elf-shlibs \
	--disable-libblkid \
	--disable-libuuid \
	--disable-uuidd \
	--disable-fsck

make
make install

rm -fv /usr/lib/{libcom_err,libe2p,libext2fs,libss}.a
sed 's/metadata_csum_seed,//' -i /etc/mke2fs.conf
