#!/bin/bash
# https://github.com/void-linux/void-packages/blob/master/srcpkgs/man-pages/template

SRC="man-pages"
PKG="$SRC"

make DESTDIR=$PWD/DES prefix=/usr install

_rm_man() {
	# Remove dup manpages.
	pushd DES/usr/share/man >/dev/null

	# coreutils
	rm -f man1/{chgrp,chmod,chown,cp,dir,dd}.1
	rm -f man1/{df,dircolors,du,install,ln,ls}.1
	rm -f man1/{mkdir,mkfifo,mknod,mv,rm,rmdir}.1
	rm -f man1/{touch,vdir}.1

	# shadow
	rm -f man5/passwd.5
	rm -f man3/getspnam.3

	# diffutils
	rm -f man1/diff.1

	# xf86-input-mouse
	rm -f man4/mouse.4

	# tzdata
	rm -f man5/tzfile.5
	rm -f man8/zdump.8
	rm -f man8/tzselect.8
	rm -f man8/zic.8

	# mdocml
# 	rm -f man7/man.7
# 	rm -f man7/mdoc.7

	# openssl-devel
	mv man3/rand.3 man3/glibc-rand.3
	mv man3/err.3 man3/glibc-err.3

	# Fix references to these manpages
	sed -i -e "s|.so man3/rand.3|.so man3/glibc-rand.3|" \
	 -e "s|.so man3/err.3|.so man3/glibc-err.3|" man3/*

	# Rename some glibc specific manpages
	mv man1/{iconv.1,glibc-iconv.1}
	mv man1/{ldd.1,glibc-ldd.1}
	mv man1/{getent.1,glibc-getent.1}

	sed 's/^\.TH SYSLOG 2/.TH KLOGCTL 3/' man2/syslog.2 > man3/klogctl.3
	popd >/dev/null

	echo -e '\n'
	cp -rv DES/* /
}

_rm_man || true
