#!/bin/bash

SRC="lz4"
PKG="$SRC"

make BUILD_STATIC=no
make BUILD_STATIC=no PREFIX=/usr install

if [[ $MULTILIB ]]; then
	make clean
	CC="gcc -m32" make BUILD_STATIC=no
	make BUILD_STATIC=no PREFIX=/usr \
		LIBDIR=/usr/lib32 \
		DESTDIR=$PWD/pkg install
	cp -av pkg/usr/lib32/* /usr/lib32
fi
