#!/bin/bash

SRC="expat"
PKG="$SRC"

./configure --prefix=/usr \
	--disable-static

make
make install

if [[ $MULTILIB ]]; then
	sed -e "/^am__append_1/ s/doc//" -i Makefile
	make clean
	CC="gcc -m32" CXX="g++ -m32" \
	./configure --prefix=/usr \
		--libdir=/usr/lib32
	make
	make DESTDIR=$PWD/pkg install
	cp -av pkg/usr/lib32/* /usr/lib32
fi
