#!/bin/bash

SRC="shadow"
PKG="$SRC"

sed -i 's/groups$(EXEEXT) //' src/Makefile.in
find man -name Makefile.in -exec sed -i 's/groups\.1 / /'   {} \;
find man -name Makefile.in -exec sed -i 's/getspnam\.3 / /' {} \;
find man -name Makefile.in -exec sed -i 's/passwd\.5 / /'   {} \;

sed -e 's@#ENCRYPT_METHOD DES@ENCRYPT_METHOD YESCRYPT@' \
	-e 's@/var/spool/mail@/var/mail@' \
	-e '/PATH=/{s@/sbin:@@;s@/bin:@@}' \
	-i etc/login.defs

# 新用户的主要组设置为 /etc/default/useradd 中的GROUP变量指定的值
sed -i '/^USERGROUPS_ENAB/s/yes/no/' etc/login.defs

touch /usr/bin/passwd
./configure --sysconfdir=/etc \
	--disable-static \
	--with-{b,yes}crypt \
	--with-group-name-max-length=32 \
	--without-libbsd

make
make exec_prefix=/usr install
make -C man install-man

pwconv
grpconv
install -Dvm600 /dev/stdin /etc/default/useradd << "EOF"
# useradd defaults file
GROUP=999
HOME=/home/users
INACTIVE=-1
EXPIRE=
SHELL=/bin/bash
SKEL=/etc/skel
CREATE_MAIL_SPOOL=no
LOG_INIT=yes
EOF

# 默认的 DES，更改密码时会报错:
# Unable to generate a salt from setting "...................................................................................................", check your settings in ENCRYPT_METHOD and the corresponding configuration for your selected hash method.
#echo -e "\nENCRYPT_METHOD YESCRYPT" >> /etc/login.defs
