#!/bin/bash
# https://git.busybox.net/buildroot
# https://gitlab.com/buildroot.org/buildroot/-/tree/master/package/elfutils/elfutils.mk
# https://github.com/buildroot/buildroot/blob/master/package/elfutils/elfutils.mk

SRC="elfutils"
PKG="libelf"

./configure --prefix=/usr \
	--disable-debuginfod \
	--enable-libdebuginfod=dummy

make -C lib
make -C libelf CFLAGS="$CFLAGS -lintl"
make -C libelf install
install -Dvm644 config/libelf.pc /usr/lib/pkgconfig
rm -fv /usr/lib/libelf.a
