#!/bin/bash

SRC="util-linux"
PKG="$SRC"

sed -i '/test_mkfds/s/^/#/' tests/helpers/Makemodule.am

./configure  \
	--bindir=/usr/bin \
	--libdir=/usr/lib \
	--runstatedir=/run \
	--sbindir=/usr/sbin \
	--disable-chfn-chsh \
	--disable-login \
	--disable-nologin \
	--disable-su \
	--disable-setpriv \
	--disable-runuser \
	--disable-pylibmount \
	--disable-{static,liblastlog2} \
	--without-python \
	ADJTIME_PATH=/var/lib/hwclock/adjtime

make
make install


if [[ $MULTILIB ]]; then
	make distclean
	mv /usr/bin/ncursesw6-config{,.tmp}
	CC="gcc -m32" \
	./configure --libdir=/usr/lib32 \
		--runstatedir=/run \
		--disable-chfn-chsh \
		--disable-login \
		--disable-nologin \
		--disable-su \
		--disable-setpriv \
		--disable-runuser \
		--disable-pylibmount \
		--disable-{static,liblastlog2} \
		--without-python \
		--without-systemd \
		--without-systemdsystemunitdir \
		ADJTIME_PATH=/var/lib/hwclock/adjtime
	mv /usr/bin/ncursesw6-config{.tmp,}
	make
	make DESTDIR=$PWD/pkg install
	cp -a pkg/usr/lib32/* /usr/lib32/
fi
