#!/bin/bash

SRC="jinja2"
PKG="python-$SRC"

pip3 --version
pip3 wheel -w dist --no-build-isolation --no-deps $PWD
pip3 install --no-index --no-user --find-links dist Jinja2
if [ -d "$HOME/.cache" ]; then
	echo -e '\n'
	rm -rfv "$HOME/.cache"
fi
