#!/bin/bash

SRC="dbus"
PKG="$SRC"

./configure --prefix=/usr \
	--sysconfdir=/etc \
	--localstatedir=/var \
	--runstatedir=/run \
	--enable-user-session \
	--disable-static \
	--disable-doxygen-docs \
	--disable-xml-docs \
	--with-system-socket=/run/dbus/system_bus_socket

make
make install
ln -sfv /etc/machine-id /var/lib/dbus
