#!/bin/bash
# https://www.linuxfromscratch.org/blfs/view/svn/basicnet/nghttp2.html

SRC="nghttp2"
PKG="$SRC"

./configure --prefix=/usr \
	--disable-static \
	--enable-lib-only

make
make install

if [[ $MULTILIB ]]; then
	make distclean
	CC="gcc -m32" CXX="g++ -m32" \
	./configure --prefix=/usr \
		--libdir=/usr/lib32 \
		--enable-lib-only
	make
	make DESTDIR=$PWD/pkg install
	cp -av pkg/usr/lib32/* /usr/lib32
fi
