#!/bin/bash
# https://www.linuxfromscratch.org/blfs/view/svn/postlfs/p11-kit.html

SRC="p11-kit"
PKG="$SRC"

sed '20,$ d' -i trust/trust-extract-compat
cat >> trust/trust-extract-compat << "EOF"
# Copy existing anchor modifications to /etc/ssl/local
/usr/libexec/make-ca/copy-trust-modifications

# Update trust stores
/usr/sbin/make-ca -r
EOF

mkdir p11-build
cd p11-build

meson setup .. \
	--prefix=/usr \
	--buildtype=release \
	-Dtrust_paths=/etc/pki/anchors
ninja
ninja install
ln -sfv pkcs11/p11-kit-trust.so /usr/lib/libnssckbi.so
