#!/bin/bash
# https://gitlab.archlinux.org/archlinux/packaging/packages/pacman
# https://sources.archlinux.org/other/pacman

SRC="pacman"
PKG="$SRC"

gitlab='https://gitlab.archlinux.org/pacman/pacman/-/commit'
PATCH1="${gitlab}/efd0c24c07b86be014a4edb5a8ece021b87e3900.patch"
PATCH2="${gitlab}/86981383a2f4380bda26311831be94cdc743649b.patch"
PATCH3="${gitlab}/478af273dfe24ded197ec54ae977ddc3719d74a0.patch"
PATCH4="${gitlab}/de11824527ec4e2561e161ac40a5714ec943543c.patch"

wget -cP .. ${PATCH1} ${PATCH2} ${PATCH3} ${PATCH4}

patch -Np1 -i ../${PATCH1##*/}
patch -Np1 -i ../${PATCH2##*/}
patch -Np1 -i ../${PATCH3##*/}
patch -Np1 -i ../${PATCH4##*/}

cat <<"EOF">> scripts/po/zh_CN.po

msgid "Splitting %s files into separate packages..."
msgstr "正在将 %s 文件拆分为单独的包..."

msgid "Splitting static library files into separate packages..."
msgstr "正在将静态库文件拆分为单独的包..."

msgid "Removing unwanted man pages..."
msgstr "正在删除不想要的手册页..."

msgid "Removing unwanted message translation files..."
msgstr "正在删除不想要的消息翻译文件..."

msgid "Finding %s files..."
msgstr "正在查找 %s 文件..."

msgid "Adding dependencies by dynamic linked library..."
msgstr "正在通过动态链接库添加依赖..."
EOF

LDFLAGS+=" -Wl,-lintl"

mkdir -v pacman-build
cd pacman-build

meson setup --prefix=/usr \
	--buildtype=release \
	-Ddoc=disabled \
	-Ddoxygen=disabled \
	-Dscriptlet-shell=/usr/bin/bash \
	-Dldconfig=/usr/sbin/ldconfig ..

ninja
ninja install

for i in PATCH{1..4}; do
	unset "$i"
done
unset gitlab
