#!/bin/bash
# https://www.linuxfromscratch.org/blfs/view/svn/general/tree.html

SRC="unix-tree"
PKG="tree"

make
make PREFIX=/usr MANDIR=/usr/share/man install
install -Dm644 ../tree.bashcomp "/usr/share/bash-completion/completions/tree"
