#!/bin/bash
# https://www.linuxfromscratch.org/blfs/view/systemd/postlfs/linux-pam.html

SRC="linux-pam"
PKG="pam"

# 1.6.0 'SIZE_MAX' undeclared
sed '/^#include "argv_parse.h"$/a\#include <stdint.h>' \
	-i modules/pam_namespace/pam_namespace.c

LDFLAGS="-Wl,-lintl $LDFLAGS"

./configure --prefix=/usr \
	--sbindir=/usr/sbin \
	--sysconfdir=/etc \
	--libdir=/usr/lib \
	--enable-securedir=/usr/lib/security

make
make install
chmod -v 4755 /usr/sbin/unix_chkpwd
