#!/bin/bash

SRC="p7zip"
PKG="$SRC"

sed '/^gzip/d' -i install.sh
sed -i '160a if(_buffer == nullptr || _size == _pos) return E_FAIL;' CPP/7zip/Common/StreamObjects.cpp

make all3
make DEST_HOME=/usr \
	DEST_MAN=/usr/share/man \
	DEST_SHARE_DOC=/usr/share/doc/p7zip install
