#!/bin/bash
# https://www.linuxfromscratch.org/blfs/view/svn/general/cmake.html

SRC="cmake"
PKG="$SRC"

sed -i '/"lib64"/s/64//' Modules/GNUInstallDirs.cmake
sed -i 's@^#  ifdef __GLIBC__$@#  if defined __GLIBC__ \&\& !defined __UCLIBC__@' \
	Source/kwsys/testDynamicLoader.cxx

./bootstrap --prefix=/usr \
	--system-libs \
	--mandir=/share/man \
	--no-system-jsoncpp \
	--no-system-cppdap \
	--no-system-librhash \
	--datadir=/share/cmake \
	--parallel=$(nproc) \
	--generator=Ninja

ninja
ninja install
