#!/bin/bash

SRC="util-linux"

mkdir -pv /var/lib/hwclock

./configure --libdir=/usr/lib \
	--runstatedir=/run \
	--disable-chfn-chsh \
	--disable-login \
	--disable-nologin \
	--disable-su \
	--disable-setpriv \
	--disable-runuser \
	--disable-pylibmount \
	--disable-static \
	--without-python \
	ADJTIME_PATH=/var/lib/hwclock/adjtime

make
make install
