#!/bin/bash

SRC="util-linux"

mkdir -pv /var/lib/hwclock

./configure --libdir=/usr/lib \
	--runstatedir=/run \
	--disable-chfn-chsh \
	--disable-login \
	--disable-nologin \
	--disable-su \
	--disable-setpriv \
	--disable-runuser \
	--disable-pylibmount \
	--disable-static \
	--disable-liblastlog2 \
	--without-python \
	ADJTIME_PATH=/var/lib/hwclock/adjtime

make
make install


if [[ $MULTILIB ]]; then
	make distclean
	CC="gcc -m32" \
	./configure --libdir=/usr/lib32 \
		--runstatedir=/run \
		--disable-chfn-chsh \
		--disable-login \
		--disable-nologin \
		--disable-su \
		--disable-setpriv \
		--disable-runuser \
		--disable-pylibmount \
		--disable-{static,liblastlog2} \
		--without-python \
		ADJTIME_PATH=/var/lib/hwclock/adjtime
	make
	make DESTDIR=$PWD/pkg install
	cp -av pkg/usr/lib32/* /usr/lib32/
fi
