#!/bin/bash

source envars
source bashrc

BOLD () { echo -e "\e[0;1m$1\e[0m"; }
RED () { echo -e "\e[1;31m$1\e[0m"; }
GREEN () { echo -e "\e[0;32m$1\e[0m"; }
ORANGE () { echo -e "\e[0;33m$1\e[0m"; }
BLUE () { echo -e "\e[1;34m$1\e[0m"; }
WHITE () { echo -e "\e[00m$1\e[0m"; }
YELLOW () { echo -e "\e[1;33m$1\e[0m"; }

unpack() {
	printf '\n'
	find . -maxdepth 1 -type d -iname "${1}*" -exec rm -rf {} +
	local archive="$(find . -maxdepth 1 -iname ${1}'-[0-9]*.tar*' -exec basename {} +)"
	if [ -n "$archive" ]; then
		printf "  -> Extracting the '$archive'... \n"
		tar xf $archive
	fi
}

get_pkg_root() {
	local srcdir="$(find . -maxdepth 1 -type d -iname ${1}\*)"
	[ -z "$srcdir" ] || cd "$srcdir"
}

make_pkg() {
	local target="$(basename $1)"
	local chapter="${1%/*}"
	local PV PVE
	chapter="${chapter##*/}"
	PV=${PWD##*/}
	PV="$(echo ${PV##*-}|sed 's/[A-Za-z]\|_//g')"
	if [ -n "$PV" ]; then PVE="-${PV}"; else PVE=""; fi
	mkdir -p "${log_dir}"
	echo $(BOLD --------------------------------------------------------------------------------)
	echo $(BOLD Building) target $(BLUE "${chapter/chapter0}$target")$(BOLD)$(WHITE)
	touch make-timestamp-marker && sleep 1
	date >"${log_dir}/${chapter/chapter0}${target}${PVE}.log"
	echo -e "KB: ${DU}\n" >>"${log_dir}/${chapter/chapter0}${target}${PVE}.log"
	bash -e "$1" >> "${log_dir}/${chapter/chapter0/}${target}${PVE}.log" 2>&1
	local marker="$(ls -l --time-style=+%s make-timestamp-marker | awk '{print$6}')"
	local now="$(date +%s)"
	echo -e "\n\nCFLAGS:: ${CFLAGS}\nCXXFLAGS:: ${CXXFLAGS}\nCPPFLAGS:: ${CPPFLAGS}\nLDFLAGS:: ${LDFLAGS}" >>"${log_dir}/${chapter/chapter0}${target}${PVE}.log"
	echo -e "\n\n$(date)\n\nTotalseconds: $((now-marker-1))\n" >>"${log_dir}/${chapter/chapter0}${target}${PVE}.log"
	echo -e "KB: $(du -skx --exclude=${BLD_ROOT#/} --exclude=lost+found --exclude var/lib $BUILDDIR)\n" >>"${log_dir}/${chapter/chapter0}${target}${PVE}.log"
	echo  -e "\n" $(BOLD Target) $(BLUE "$target") $(WHITE)$(BOLD OK)
	echo --------------------------------------------------------------------------------$(WHITE)
	cd "${SRC_ARCHIVE}"
	find . -maxdepth 1 -type d -iname "${2}*" ! -name . -exec rm -rf {} +
}

for i in $@
do
	pushd "${SRC_ARCHIVE}" >/dev/null
	grep  '^SRC=' "${status_dir}/$i" >tmp
	. ./tmp

	DU="$(du -skx --exclude=${BLD_ROOT#/} --exclude=lost+found --exclude var/lib $BUILDDIR)"

	if [ -n "${SRC}" ]; then
		unpack "${SRC}"
		get_pkg_root "${SRC}"
	fi
	source "${status_dir}/envars"
	make_pkg "${status_dir}/$i" "$SRC"
	unset DU
	popd >/dev/null
done
