#!/bin/bash
# https://gitweb.gentoo.org/repo/gentoo.git/tree/sys-libs/queue-standalone
# https://gitweb.gentoo.org/repo/gentoo.git/tree/app-arch/libarchive/libarchive-3.7.0.ebuild
# https://linuxfromscratch.org/blfs/view/git/general/libarchive.html
# 需要 sys/queue.h

SRC="libarchive"
PKG="$SRC"

_env=(
	--disable-static
	ac_cv_func_{setlocale,stat{,v}fs}=no
	ac_cv_header_sys_stat{,v}fs_h=no
)

./configure --prefix=/usr ${_env[@]}

make
make install

if [[ $MULTILIB ]]; then
	make distclean
	PKG_CONFIG_PATH="/usr/lib32/pkgconfig" \
	CC="gcc -m32" CXX="g++ -m32" \
	./configure --prefix=/usr \
		--libdir=/usr/lib32 ${_env[@]}
	make
	make DESTDIR=$PWD/pkg install
	cp -av pkg/usr/lib32/* /usr/lib32
fi
